<!DOCTYPE html>
<html>
<head>
<style type="text/css"> 
<!-- 
 
 #navbar ul { 
  margin: 0; 
  padding: 5px; 
  list-style-type: none; 
  text-align: center; 
  background-color: #000; 
  } 
 
#navbar ul li {  
  display: inline;
  font-size: 18px; 
  } 
 
#navbar ul li a { 
  text-decoration: none; 
  padding: .2em 1em; 
  color: #fff; 
  background-color: #000; 
  } 
 
#navbar ul li a:hover { 
  color: #000; 
  background-color: #fff; 
  } 


 
--> 
</style>
</head>
<body>

            <nav id="navbar">
                <ul>
                    <li><a href="index.php" class="active">Home</a></li>
                    <li><a href="task1.php">Task 1</a></li>
                    <li><a href="task2.php">Task 2</a></li>
                    <li><a href="task3.php">Task 3</a></li>
                    <li><a href="task4.php">Task 4</a></li>
                </ul>
            </nav>

</body>
</html>